from rubiks_cube_gym.envs.rubiks_cube_222 import RubiksCube222Env
from rubiks_cube_gym.envs.rubiks_cube_222_lbl import RubiksCube222EnvLBL
from rubiks_cube_gym.envs.rubiks_cube_222_ortega import RubiksCube222EnvOrtega
from rubiks_cube_gym.envs.pyraminx_wo_tips import PyraminxWoTipsEnv
from rubiks_cube_gym.envs.pyraminx_wo_tips_lbl import PyraminxWoTipsEnvLBL
from rubiks_cube_gym.envs.skewb import SkewbEnv
from rubiks_cube_gym.envs.skewb_sarah import SkewbEnvSarah
