from rubiks_cube_gym.envs.rubiks_cube_222 import RubiksCube222Env
from rubiks_cube_gym.envs.rubiks_cube_222_lbl import RubiksCube222EnvLBL
from rubiks_cube_gym.envs.rubiks_cube_222_ortega import RubiksCube222EnvOrtega
